---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest  # This is the container image (nginx in this case)
    ports:
    - containerPort: 80 
