
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: junior
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  verbs: ["get", "watch", "list"]
  resources: ["pods", "pods/log"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader
subjects:
- kind: ServiceAccount  # Corrected "Serviceaccount" to "ServiceAccount"
  name: junior           # Name of the service account
  namespace: default     # Namespace where the service account is located

roleRef:
  kind: ClusterRole
  name: pod-reader      # Name of the ClusterRole being bound
  apiGroup: rbac.authorization.k8s.io
