
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: senior
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all access
rules:
- apiGroups: ["*"]
  verbs: ["*"]
  resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all access
subjects:
- kind: ServiceAccount  # Corrected "Serviceaccount" to "ServiceAccount"
  name: senior           # Name of the service account
  namespace: default     # Namespace where the service account is located

roleRef:
  kind: ClusterRole
  name: all access       # Name of the ClusterRole being bound
  apiGroup: rbac.authorization.k8s.io
