apiVersion: v1
kind: Pod
metadata:
  name: my-tolerant-pod
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "high-availability"
    effect: "NoExecute"
  containers:
  - name: my-container
    image: nginx
